/*

 BACKGROUNDMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 36
   Tile set      : Z:\home\xacto\Dropbox\Projects\gb\10_Development\5-of-a-Kind\res\backgroundData.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define backgroundMapWidth 20
#define backgroundMapHeight 36
#define backgroundMapBank 0

extern unsigned char backgroundMap[];

/* End of BACKGROUNDMAP.H */
