/*

 NAMEINPUTMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : backgroundData.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define nameInputMapWidth 20
#define nameInputMapHeight 18
#define nameInputMapBank 0

extern unsigned char nameInputMap[];

/* End of NAMEINPUTMAP.H */
