/*

 OPTIONSMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : Z:\home\xacto\github\5ofaKind\res\backgroundData.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define optionsMapWidth 20
#define optionsMapHeight 18
#define optionsMapBank 0

extern unsigned char optionsMap[];

/* End of OPTIONSMAP.H */
