/*

 SCOREMAP3.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : Z:\home\xacto\github\5ofaKind\res\backgroundData.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define scoreMap3Width 20
#define scoreMap3Height 18
#define scoreMap3Bank 0

extern unsigned char scoreMap3[];

/* End of SCOREMAP3.H */
