/*

 SCREEN_START_MAP_NEW.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : D:\GitHub\5ofaKind\res\backgroundData.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define startMapWidth 20
#define startMapHeight 18
#define startMapBank 0

extern unsigned char startMap[];

/* End of SCREEN_START_MAP_NEW.H */
